
###################  项目启动端口  ###################
server:
  ssl:
    enabled: false
    key-store: classpath:sb.keystore
    key-store-password: changeme
    key-store-type: JKS
    key-alias: sbkey
#https://my.oschina.net/kingchen8080/blog/994367




