
###################  项目启动端口  ###################
server:
  ssl:
    enabled: false
    key-store: classpath:sb.keystore
    key-store-password: changeme
    key-store-type: JKS
    key-alias: sbkey
#https://my.oschina.net/kingchen8080/blog/994367


datasource:
  url: jdbc:mysql://localhost:3307/uaas-saas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
  username: root
  password: root
  sql: SELECT * FROM t_sys_user WHERE account = ?

